version: "3"

services:
  pymander-dev:
    container_name: doit
    image: dwrolvink/doit:latest
    ports:
      - target: 5000
        published: 8080
        mode: host #"8080:5000/tcp"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - './app:/app/'     
    stop_signal: SIGINT # gracefully stop flask